version: 2

registries:
  docker-hardened-images:
    type: docker-registry
    url: dhi.io
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:42"
      timezone: "Europe/Oslo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:42"
      timezone: "Europe/Oslo"

  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - "docker-hardened-images"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:42"
      timezone: "Europe/Oslo"
