management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      access: read_only

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: 'valgdata'

server:
  servlet:
    context-path: '/valgdata'