name: 'Dependency Review and Graph'
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v7

      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6.3.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v5.0.0
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
          allow-licenses: MIT, Apache-2.0, EPL-2.0, BSD-3-Clause, BSD-2-Clause, CPL-1.0
          # JUnit 6 and Spring 7 har problemer med scannig de har EPL-2.0 and Apache-2.0.
          allow-dependencies-licenses: >
            pkg:maven/org.junit.jupiter/junit-jupiter-engine,
            pkg:maven/org.junit.jupiter/junit-jupiter-params,
            pkg:maven/org.junit.platform/junit-platform-commons,
            pkg:maven/org.junit.platform/junit-platform-engine,
            pkg:maven/org.junit.platform/junit-platform-launcher,
            pkg:maven/org.springframework/spring-web
