name: Promote dev to prod
on: workflow_dispatch

env:
  image_name: smia-valgdata
  registry: ghcr.io
  registry_path: kartverket

jobs:
  deploy-argo:
    permissions:
      id-token: write
    uses: kartverket/smia-apps/.github/workflows/promote-app-octo-sts.yml@main
    with:
      application: smia-valgdata
      namespace: "smia-tjenester-main"
      identity: restapi