name: Validate Synthetic Monitoring Config

on:
  push:
    branches:
      - main
    paths:
      - synthetic-monitoring.yaml
  pull_request:
    paths:
      - synthetic-monitoring.yaml

jobs:
  call-synthetic-monitoring:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: kartverket/github-workflows/.github/workflows/synthetic-monitoring.yaml@c3fabaec85ee208e5f10782ac71b5a82b30c6bb3 # v4.13.2
